[project]
name = "facelandmarks"
version = "0.1.0"
description = "Detect facial landmarks from an image"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=2.3.2",
    "flask-cors>=4.0.2",
    "hdface>=0.1.3",
    "opencv-python>=4.10.0.84",
    "pillow>=10.4.0",
    "python-dotenv>=1.1.0",
    "torch>=2.4.1",
    "torchvision>=0.19.1",
]
